#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=on
	active_color=0xf02c2e34
	# inactive_color=0xc02c2e34
	background_color=0xf02c2e34
	blacklist="KakaoTalk,xfce4-clipman,xfce4-notifyd,xfce4-screenshooter,xfce4-systemload-plugin,xfce4-taskmanager,xfce4-weather-plugin"
)

borders "${options[@]}"